Repository databrickslabs/dbldatagen, pull requests merged in 2024-06, with the labels that each got.

#277 Feature distribution changes - migrated tests to Pytest, use of abstract base classes
  CHANGELOG.md
  dbldatagen/distributions/data_distribution.py
  tests/test_distributions.py
Labels: code quality

#278 PR To test updates to process
  CHANGELOG.md
Labels: test process artifact

#258 Feature standard datasets - part 1
  CHANGELOG.md
  Pipfile.lock
  README.md
  dbldatagen/__init__.py
  dbldatagen/datasets/__init__.py
  dbldatagen/datasets/basic_user.py
  dbldatagen/datasets/dataset_provider.py
  dbldatagen/datasets/multi_table_telephony_provider.py
  dbldatagen/datasets_object.py
  docs/source/APIDOCS.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/using_standard_datasets.rst
  docs/utils/mk_quick_index.py
  setup.py
  tests/__init__.py
  tests/test_standard_dataset_providers.py
  tests/test_standard_datasets.py
Labels: enhancement

#286 Feature standard datasets - part 2
  CHANGELOG.md
  dbldatagen/datasets/__init__.py
  dbldatagen/datasets/basic_geometries.py
  dbldatagen/datasets/basic_process_historian.py
  dbldatagen/datasets/basic_telematics.py
  dbldatagen/datasets/benchmark_groupby.py
  tests/test_standard_dataset_providers.py
Labels: enhancement
